### PR TITLE
update model-3.0

### PR DESCRIPTION
**Pull request by DaiYuanchuan**

### CODE REVIEW

**Comment by andresribeiro** [comment]
Hey @DaiYuanchuan, did you change the model files to the ones found [here](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model), in the NSFWJS repository?

**Comment by DaiYuanchuan** [comment]
> Hey @DaiYuanchuan, did you change the model files to the ones found [here](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model), in the NSFWJS repository?

Yes, you can try. I've changed to a more accurate model. It comes from [here](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model)

**Comment by andresribeiro** [comment]
> Yes, you can try. I've changed to a more accurate model. It comes from [here](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model)

I appreciate your interest in improving the model, but these files were modified 2 years ago 😕

The current files are taken from [here](https://github.com/GantMan/nsfw_model), where it has a more recent version

**Comment by DaiYuanchuan** [comment]
Really? Why do I feel that the current model is not so accurate.

> > Yes, you can try. I've changed to a more accurate model. It comes from [here](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model)
> 
> I appreciate your interest in improving the model, but these files were modified 2 years ago 😕
> 
> The current files are taken from [here](https://github.com/GantMan/nsfw_model), where it has a more recent version

Really? Why do I feel that the current model is not so accurate，the existing models can not recognize some images accurately

**Comment by andresribeiro** [comment]
> Really? Why do I feel that the current model is not so accurate，the existing models can not recognize some images accurately

Well, if you have found any false positives, you can report them and help improve the model

**Comment by DaiYuanchuan** [comment]
> > Really? Why do I feel that the current model is not so accurate，the existing models can not recognize some images accurately
> 
> Well, if you have found any false positives, you can report them and help improve the model

This model hasn't been updated for two years...😓

**Comment by andresribeiro** [comment]
> This model hasn't been updated for two years...

The [NSFWJS example model](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model) has not been updated for some time, but [NSFW_MODEL](https://github.com/GantMan/nsfw_model), which powers NSFWJS, was updated in May 2020. 

If you open an issue of a false positive they add the image to the model, like [in this issue here](https://github.com/infinitered/nsfwjs/issues/513). There will probably release new models, but they just don't do it too often

**Comment by DaiYuanchuan** [comment]
> > This model hasn't been updated for two years...
> 
> The [NSFWJS example model](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model) has not been updated for some time, but [NSFW_MODEL](https://github.com/GantMan/nsfw_model), which powers NSFWJS, was updated in May 2020.
> 
> If you open an issue of a false positive they add the image to the model, like [in this issue here](https://github.com/infinitered/nsfwjs/issues/513). There will probably release new models, but they just don't do it too often

I can't recognize some images accurately with [this model](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/quant_mid), but [this model](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model) can
I don't know exactly why

**Comment by andresribeiro** [comment]
> I can't recognize some images accurately with [this model](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/quant_mid), but [this model](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model) can
> I don't understand why，so I think [this model](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model) is more accurate

Hmmm... I will do some tests with these models at the weekend

**Comment by DaiYuanchuan** [comment]
> 
> 
> > I can't recognize some images accurately with [this model](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/quant_mid), but [this model](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model) can
> > I don't understand why，so I think [this model](https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model) is more accurate
> 
> Hmmm... I will do some tests with these models at the weekend

Hi，What were the results of the test？I recently encountered a new problem，I started the NSFWJS container with Docker，and then when it gets a lot of requests，it takes up a lot of memory，memory is occupied for a long time and will not be freed，this will cause my server to run out of memory，do you have any solutions？？？

**Comment by andresribeiro** [comment]
> Hi，What were the results of the test？I recently encountered a new problem，I started the NSFWJS container with Docker，and then when it gets a lot of requests，it takes up a lot of memory，memory is occupied for a long time and will not be freed，this will cause my server to run out of memory，do you have any solutions？？？

I'm still a little confused about which version is the current one, so what about opening an issue at NSFWJS asking about this?

It uses a lot of memory because NSFWJS uses TensorFlow. In the Dockerfile I'm using Ubuntu, but maybe we can use Alpine Linux. I'm just not sure how to do this

**Comment by DaiYuanchuan** [comment]
> 
> 
> > Hi，What were the results of the test？I recently encountered a new problem，I started the NSFWJS container with Docker，and then when it gets a lot of requests，it takes up a lot of memory，memory is occupied for a long time and will not be freed，this will cause my server to run out of memory，do you have any solutions？？？
> 
> I'm still a little confused about which version is the current one, so what about opening an issue at NSFWJS asking about this?
> 
> It uses a lot of memory because NSFWJS uses TensorFlow. In the Dockerfile I'm using Ubuntu, but maybe we can use Alpine Linux. I'm just not sure how to do this



> 
> 
> > Hi，What were the results of the test？I recently encountered a new problem，I started the NSFWJS container with Docker，and then when it gets a lot of requests，it takes up a lot of memory，memory is occupied for a long time and will not be freed，this will cause my server to run out of memory，do you have any solutions？？？
> 
> I'm still a little confused about which version is the current one, so what about opening an issue at NSFWJS asking about this?
> 
> It uses a lot of memory because NSFWJS uses TensorFlow. In the Dockerfile I'm using Ubuntu, but maybe we can use Alpine Linux. I'm just not sure how to do this

I tried using this(https://github.com/infinitered/nsfwjs/blob/master/example/node_demo/server.js) to build my container and I found that it has very good memory control, but I found that the 'jpeg-js' module doesn't seem to decode PNG images，do you have any good ideas？

**Comment by andresribeiro** [comment]
Maybe convert PNG images to JPEG, but that would increase processing and add a delay, so it wouldn't work very well

**Comment by andresribeiro** [comment]
i've added support for PNG and updated the model

**Pull request closed without merging**
